// Sample cafe data embedded for instant demo
export const CAFE_SAMPLE = [
  { _rowId:1, reviewer:"유저A", rating:"5", text:"분위기가 정말 좋고 인테리어가 예뻐요. 사진 찍기 딱 좋은 곳!" },
  { _rowId:2, reviewer:"유저B", rating:"3", text:"커피 맛은 괜찮은데 가격이 너무 비싸요. 아메리카노가 6천원이라니..." },
  { _rowId:3, reviewer:"유저C", rating:"5", text:"디저트가 정말 맛있어요! 크로플이랑 케이크 다 훌륭합니다." },
  { _rowId:4, reviewer:"유저D", rating:"4", text:"조용해서 공부하기 좋아요. 콘센트도 많고 와이파이 빠릅니다." },
  { _rowId:5, reviewer:"유저E", rating:"2", text:"주차가 너무 불편하고 자리가 좁아요. 커피 맛은 보통." },
  { _rowId:6, reviewer:"유저F", rating:"5", text:"뷰가 최고! 창가 자리에서 보는 야경이 너무 아름다워요." },
  { _rowId:7, reviewer:"유저G", rating:"4", text:"라떼 아트가 예쁘고 원두 퀄리티가 좋아요. 핸드드립 추천합니다." },
  { _rowId:8, reviewer:"유저H", rating:"3", text:"분위기는 좋은데 음료가 너무 달아요. 당도 조절이 안 돼요." },
  { _rowId:9, reviewer:"유저I", rating:"5", text:"작업하기 최고의 카페! 넓은 테이블, 조용한 음악, 긴 영업시간." },
  { _rowId:10, reviewer:"유저J", rating:"4", text:"케이크 종류가 다양하고 다 맛있어요. 딸기 케이크 강추!" },
  { _rowId:11, reviewer:"유저K", rating:"2", text:"서비스가 불친절하고 대기 시간이 너무 길어요." },
  { _rowId:12, reviewer:"유저L", rating:"5", text:"인테리어가 독특하고 감성적이에요. SNS 핫플레이스 답습니다." },
  { _rowId:13, reviewer:"유저M", rating:"4", text:"가성비 좋아요! 아메리카노 3500원에 리필도 됩니다." },
  { _rowId:14, reviewer:"유저N", rating:"3", text:"스콘이 맛있는데 커피가 좀 약해요. 에스프레소 샷 추가 필요." },
  { _rowId:15, reviewer:"유저O", rating:"5", text:"노트북 작업하기 완벽해요. 1인 좌석에 개인 콘센트까지!" },
  { _rowId:16, reviewer:"유저P", rating:"4", text:"핸드드립 커피가 진짜 맛있어요. 원두도 직접 로스팅한다고 합니다." },
  { _rowId:17, reviewer:"유저Q", rating:"2", text:"음료 양이 적고 가격 대비 아쉬워요. 빙수는 괜찮았습니다." },
  { _rowId:18, reviewer:"유저R", rating:"5", text:"테라스가 넓고 펫 동반 가능해서 좋아요! 뷰도 좋고." },
  { _rowId:19, reviewer:"유저S", rating:"4", text:"마카롱이 유명한 곳인데 역시 맛있어요. 포장도 예쁩니다." },
  { _rowId:20, reviewer:"유저T", rating:"3", text:"주말엔 너무 붐비고 시끄러워요. 평일에 가면 좋을 듯." },
  { _rowId:21, reviewer:"유저U", rating:"5", text:"분위기 맛집! 빈티지 인테리어에 LP판 틀어주는 감성 카페." },
  { _rowId:22, reviewer:"유저V", rating:"4", text:"콜드브루가 깔끔하고 좋아요. 텀블러 할인도 됩니다." },
  { _rowId:23, reviewer:"유저W", rating:"5", text:"공부 카페로 최고예요. 스터디룸도 있고 음료 무한리필!" },
  { _rowId:24, reviewer:"유저X", rating:"2", text:"에어컨이 너무 세서 추웠어요. 맛은 그냥 평범합니다." },
  { _rowId:25, reviewer:"유저Y", rating:"5", text:"티라미수가 인생 디저트! 케이크도 다 수제라 맛있어요." },
  { _rowId:26, reviewer:"유저Z", rating:"4", text:"루프탑에서 보는 전망이 좋아요. 데이트 코스로 추천합니다." },
  { _rowId:27, reviewer:"유저AA", rating:"3", text:"커피는 맛있는데 자리가 불편해요. 의자가 딱딱합니다." },
  { _rowId:28, reviewer:"유저BB", rating:"5", text:"가격 대비 양이 많고 맛있어요. 세트 메뉴가 가성비 최고!" },
  { _rowId:29, reviewer:"유저CC", rating:"4", text:"조용한 분위기에서 책 읽기 좋아요. 독서 모임에 딱입니다." },
  { _rowId:30, reviewer:"유저DD", rating:"5", text:"라떼가 부드럽고 진해요. 바리스타가 직접 내려주는 퀄리티!" },
  { _rowId:31, reviewer:"유저EE", rating:"3", text:"브런치 메뉴는 맛있는데 대기가 30분 이상이에요." },
  { _rowId:32, reviewer:"유저FF", rating:"5", text:"정원이 있는 카페! 꽃이 예쁘고 사진 찍기 좋아요." },
  { _rowId:33, reviewer:"유저GG", rating:"4", text:"와플이 바삭하고 아이스크림이랑 잘 어울려요. 디저트 맛집!" },
  { _rowId:34, reviewer:"유저HH", rating:"2", text:"웨이팅이 길고 좌석이 불편합니다. 회전율 안 좋아요." },
  { _rowId:35, reviewer:"유저II", rating:"5", text:"스터디 카페처럼 집중하기 좋아요. 타이머도 있고 조용합니다." },
  { _rowId:36, reviewer:"유저JJ", rating:"4", text:"싱글오리진 커피가 다양해요. 에티오피아 예가체프 추천!" },
  { _rowId:37, reviewer:"유저KK", rating:"5", text:"야외 테라스에서 석양 보면서 커피 마시는 게 힐링이에요." },
  { _rowId:38, reviewer:"유저LL", rating:"3", text:"당근케이크가 맛있는데 커피는 평범해요. 디저트 위주로 주문하세요." },
  { _rowId:39, reviewer:"유저MM", rating:"4", text:"학생 할인 되고 아메리카노가 저렴해서 자주 와요." },
  { _rowId:40, reviewer:"유저NN", rating:"5", text:"감성 인테리어에 조명이 예뻐요. 데이트 장소로 완벽!" },
];
